### ISSUE TITLE
libusb 1.0.24

### ISSUE THREAD

**Issue by redDwarf03** [woodemi/quick_usb#45]
hello

could you migrate the project to libusb 1.0.24 in each platform please
thx

**Comment by Sunbreak** [comment]
Why do we need libusb 1.0.24?

**Comment by fanchou** [comment]
v1.0.25 is release.

**Comment by Sunbreak** [comment]
Is there any benefit to upgrade? More APIs? More reliable? More compatiliblity?

Is there any clue or changelog?

**Comment by Sunbreak** [comment]
Upgrade to libusb-v1.0.25 requires `re-generation` of https://github.com/woodemi/libusb.dart, i.e. `flutter run ffigen`

**`ffi` and `ffigen` are quite different to one year ago**

There are `ffi-1.1.2` and `ffigen-2.4.2` inside [`libusb.dart`'s lock file](https://github.com/woodemi/libusb.dart/blob/ba945791b21786f25392d96a57ce926eb2295eef/pubspec.lock#L81-L94)

```yaml
  ffi:
    dependency: "direct main"
    description:
      name: ffi
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.2"
  ffigen:
    dependency: "direct dev"
    description:
      name: ffigen
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.4.2"
```

Lastest on Pub are https://pub.dev/packages/ffi/versions/1.2.0-dev.0 and https://pub.dev/packages/ffigen/versions/5.0.0-dev.0

PRs are welcome if you're interested
